### ISSUE TITLE
Group messages don't always send

### ISSUE THREAD

**Issue by GrayHatter** [irungentoo/toxcore#1283]
it uTox if you try to send the following text

```
Core was generated by `qtox -P zetok'.                                                                                                                                        
Program terminated with signal SIGSEGV, Segmentation fault.                                                                                                                   
#0  0x00007f7bc679bc3f in pushbuf_flush (push=push@entry=0x7f7bdb2f68e0) at /var/tmp/portage/x11-libs/libdrm-2.4.52/work/libdrm-2.4.52/nouveau/pushbuf.c:425                  
425     /var/tmp/portage/x11-libs/libdrm-2.4.52/work/libdrm-2.4.52/nouveau/pushbuf.c: No such file or directory.                                                              
(gdb) bt                                                                                                                                                                      
#0  0x00007f7bc679bc3f in pushbuf_flush (push=push@entry=0x7f7bdb2f68e0) at /var/tmp/portage/x11-libs/libdrm-2.4.52/work/libdrm-2.4.52/nouveau/pushbuf.c:425                  
#1  0x00007f7bc679c836 in nouveau_pushbuf_kick (push=0x7f7bdb2f68e0, chan=<optimized out>)                                                                                    
    at /var/tmp/portage/x11-libs/libdrm-2.4.52/work/libdrm-2.4.52/nouveau/pushbuf.c:774                                                                                       
```

It will do nothing... But if you remove the extra spaces at the end of the last line, it will send. Or if you remove any one(1) line it will also send. see notsecure/utox#714

Good luck!

**Comment by zetok** [comment]
[It was a problem in qTox](https://github.com/tux3/qTox/issues/940#issuecomment-78958152), now fixed. I suspect that implementation of message splitting in µTox doesn't work as it should.
