### ISSUE TITLE
Segfault when starting daemon

### ISSUE THREAD

**Issue by MAH69IK** [irungentoo/toxcore#1341]
Hello.
I'm receiving this error, when try to star daemon:
**tox-bootstrapd[20201]: segfault at 0 ip 00007ff55268a300 sp 00007ffe741d1930 error 4 in libc-2.20.so[7ff552620000+18f000]**

I installed Tox from Gentoo overlay with daemon option.
Log:
```
May 10 20:08:30 [tox-bootstrapd] Running "tox-bootstrapd" version 2014101200._
May 10 20:08:30 [tox-bootstrapd] Successfully read:_
May 10 20:08:30 [tox-bootstrapd] 'pid_file_path': /var/run/tox-bootstrapd/tox-bootstrapd.pid_
May 10 20:08:30 [tox-bootstrapd] 'keys_file_path': /var/lib/tox-bootstrapd/keys_
May 10 20:08:30 [tox-bootstrapd] 'port': 33445_
May 10 20:08:30 [tox-bootstrapd] 'enable_ipv6': true_
May 10 20:08:30 [tox-bootstrapd] 'enable_ipv4_fallback': true_
May 10 20:08:30 [tox-bootstrapd] 'enable_lan_discovery': false_
May 10 20:08:30 [tox-bootstrapd] 'enable_tcp_relay': true_
May 10 20:08:30 [tox-bootstrapd] Read 3 TCP ports:_
May 10 20:08:30 [tox-bootstrapd] Port #0: 443_
May 10 20:08:30 [tox-bootstrapd] Port #1: 3389_
May 10 20:08:30 [tox-bootstrapd] Port #2: 33445_
May 10 20:08:30 [tox-bootstrapd] 'enable_motd': false_
May 10 20:08:30 [tox-bootstrapd] General config read successfully_
May 10 20:08:30 [/etc/init.d/tox-dht-daemon] start-stop-daemon: failed to start `/usr/bin/tox-bootstrapd'
May 10 20:08:30 [kernel] [ 4255.236445] tox-bootstrapd[20201]: segfault at 0 ip 00007ff55268a300 sp 00007ffe741d1930 error 4 in libc-2.20.so[7ff552620000+18f000]
May 10 20:08:30 [/etc/init.d/tox-dht-daemon] ERROR: tox-dht-daemon failed to start
```

Config:
grep -v '^//' /etc/tox-bootstrapd.conf
```
port = 33445
keys_file_path = "/var/lib/tox-bootstrapd/keys"
pid_file_path = "/var/run/tox-bootstrapd/tox-bootstrapd.pid"
enable_ipv6 = true
enable_ipv4_fallback = true
enable_lan_discovery = false
enable_tcp_relay = true
tcp_relay_ports = [443, 3389, 33445]
enable_motd = false
motd = "tox-bootstrapd"
bootstrap_nodes = (
  { // sonOfRa, DE
    address = "2a01:4f8:191:64d6::1"
    port = 33445
    public_key = "04119E835DF3E78BACF0F84235B300546AF8B936F035185E2A8E9E0A67C8924F"
  },
  { // SylvieLorxu, NL
    address = "2a02:2308::216:3eff:fe82:eaef"
    port = 33445
    public_key = "4B2C19E924972CB9B57732FB172F8A8604DE13EEDA2A6234E348983344B23057"
  },
  { // Munrek, FR
    address = "2001:bc8:3698:101::1"
    port = 33445
    public_key = "E398A69646B8CEACA9F0B84F553726C1C49270558C57DF5F3C368F05A7D71354"
  },
  { // Impyy, NL
    address = "2a03:b0c0:2:d0::16:1"
    port = 33445
    public_key = "788236D34978D1D5BD822F0A5BEBD2C53C64CC31CD3149350EE27D4D9A2F9B6B"
  },
  { // Manolis, DE
    address = "2001:6f8:1c3c:babe::14:1"
    port = 33445
    public_key = "461FA3776EF0FA655F1A05477DF1B3B614F7D6B124F7DB1DD4FE3C08B03B640F"
  },
  { // Kr9r0x, UK
    address = "2a01:7e00::f03c:91ff:fe69:9912"
    port = 33445
    public_key = "C4CEB8C7AC607C6B374E2E782B3C00EA3A63B80D4910B8649CCACDD19F260819"
  },
  { // fluke571, SI
    address = "2001:1470:fbfe::109"
    port = 33445
    public_key = "3CEE1F054081E7A011234883BC4FC39F661A55B73637A5AC293DDF1251D9432B"
  }
)
```

Arch: x86_64
Kernel: 3.18.11
Glibc: 2.20-r2

**Comment by zetok** [comment]
reproducible with: `$ tox-bootstrapd /etc/tox-bootstrapd.conf`:
```
Program received signal SIGSEGV, Segmentation fault.
__GI__IO_fwrite (buf=0x7fffffffd760, size=1, count=64, fp=0x0) at iofwrite.c:41
41	iofwrite.c: No such file or directory.
(gdb) bt
#0  __GI__IO_fwrite (buf=0x7fffffffd760, size=1, count=64, fp=0x0) at iofwrite.c:41
#1  0x0000555555555f81 in manage_keys (dht=0x7ffff7fca010, 
    keys_file_path=0x55555575a310 "/var/lib/tox-bootstrapd/keys")
    at ../other/bootstrap_daemon/tox-bootstrapd.c:108
#2  0x0000555555557698 in main (argc=2, argv=0x7fffffffd9c8)
    at ../other/bootstrap_daemon/tox-bootstrapd.c:609
```

**Comment by irungentoo** [comment]
Fixed in: https://github.com/irungentoo/toxcore/commit/06188e981801d18c103d1525f5d463b2967fcd88

**Comment by MAH69IK** [comment]
Thank you, this helped. But the directory should be created manually...
