### ISSUE TITLE
bad length for tox_hash crashes libsodium

### ISSUE THREAD

**Issue by benwaffle** [irungentoo/toxcore#1456]
pass `-1` to `tox_hash`

```gdb
#0  0x00007ffff4a64910 in ?? () from /usr/lib/libsodium.so.13
#1  0x00007ffff4a664af in crypto_hash_sha256_update () from /usr/lib/libsodium.so.13
#2  0x00007ffff4a66739 in crypto_hash_sha256 () from /usr/lib/libsodium.so.13
#3  0x00007ffff4ccaec5 in tox_hash () from /usr/lib/libtoxcore.so.0
```

**Comment by irungentoo** [comment]
the length of that function is an unsigned int.
